### ISSUE TITLE
Add DSA code for binary search

### ISSUE THREAD

**Issue by awesometushar000** [awesometushar000/DSA-Codes#1]
Adhere to these requirements
1) Do PR with code written in CPP only.
2) Plagiarism is strictly rejected.
3) Write time complexity and auxiliary space complexity in comments.
4) Take user-defined input.

**Comment by codegoggins** [comment]
Hey @awesometushar000  I would like to contribute to this please assign this task.

**Comment by awesometushar000** [comment]
> Hey @awesometushar000 I would like to contribute to this please assign this task.

Ok you can contribute

**Comment by codegoggins** [comment]
Thanks Please assign
