### ISSUE TITLE
Add code for Chaining in Hashing 

### ISSUE THREAD

**Issue by awesometushar000** [awesometushar000/DSA-Codes#7]
Adhere to these requirements

1) Do PR with code written in CPP only.
2) Plagiarism is strictly rejected.
3) Write time complexity and auxiliary space complexity in comments.
4) Take user-defined input.
5) Perform search, insert, and delete operations on key.

**Comment by Adiii1436** [comment]
Hello! I want to work on this issue! I am familiar with hashing.

**Comment by awesometushar000** [comment]
> Hello! I want to work on this issue! I am familiar with hashing.

Task Assigned to You !! Happy Hacking
